Adding routes and migration script for bookmarking
cuappdev/volume-backend pull request #126
Opened 2023-11-12 18:56 UTC by Aayush-Agnihotri

## Overview
Created new routes for bookmarking articles, flyers, and magazines. Removed the previous "numBookmarkedArticles" field from the user model. Added bookmarkedArticles, bookmarkedMagazines, and bookmarkedFlyers fields to the user model. Created migration script to migrate the database. Removed "numBookmarkedArticles" field from WeeklyDebrief model and refactored associated code to prevent any errors.

## Screenshots
Running "migrate-mongo up" results in
![image](https://github.com/cuappdev/volume-backend/assets/68517064/dbc89def-b739-494c-a7da-a1f377caa338)

Running "migrate-mongo down" results in
![image](https://github.com/cuappdev/volume-backend/assets/68517064/d24dc9f3-e55b-49b8-8ba2-4df1acd9f65d)

2023-11-13 04:22 UTC, vinnie4k submitted a review, later dismissed
Great work! I'll approve this for now since @cindy-x-liang needs this to work. Can you write a few test cases as well for the routes? I'm not sure if you tested with the GraphQL playground, but I would test with that to make sure the routes are working.

2023-11-14 15:46 UTC, zachseidner1 requested changes
Nice work! Looks like you've learned everything pretty quickly :) 
As Vin said, it would be good to add some unit tests for these routes. Also make sure to address my comment on using `followedOrganizations`! I'm worried your code may not work as expected. What testing have you done so far?

2023-11-14 15:46 UTC, zachseidner1 commented on migrations/update-users-model.js
I think you should be able to do this using `updateMany` like I provided in the example. This way you don't have to get all the users and do a loop through the collection.

2023-11-14 15:46 UTC, zachseidner1 commented on src/repos/UserRepo.ts
> +    user.followedOrganizations.splice(articleIndex, 1);
Why are you doing this for `followedOrganizations` for bookmarking articles? Shouldn't you use `bookedmarkedArticles`?

2023-11-14 15:46 UTC, zachseidner1 commented on src/repos/UserRepo.ts
> +    user.followedOrganizations.splice(magazineIndex, 1);
Similar to above comment

2023-11-14 15:46 UTC, zachseidner1 commented on src/repos/UserRepo.ts
> +    user.followedOrganizations.splice(flyerIndex, 1);
Similar to above comment

2023-11-17 04:08 UTC, vinnie4k submitted a review, later dismissed
Write some test cases and if it works then you should be good to go. If possible, I want this out ASAP so that Cindy can start working on notifications.

2023-11-17 19:07 UTC, zachseidner1 submitted a review, later dismissed
Looks good. Please make sure you have tested the code in some way before merging! But I understand we want to get this out quickly so if you merge without writing unit tests it's ok. Just make sure you have tested the code _somehow_

2023-11-21 01:03 UTC, vinnie4k approved these changes
Good to go.

2023-11-21 03:37 UTC, merged