Isaac/magazines weeklydebrief
cuappdev/volume-backend pull request #66
Opened 2023-03-12 21:01 UTC by isaachan100

## Overview
Added magazines to weekly debrief feature
(note: forgot to checkout back to main branch after making earlier pr, sorry about duplicated files)

## Changes Made

- updated weekly debrief and user model types
- changed logic in controllers to support magazines in weekly debrief
- created mutation: readMagazine(...): User
- updated mutation: getWeeklyDebrief(...): [WeeklyDebrief!]!

## Test Coverage

ran the two new mutations locally and verified the outputs

2023-03-14 18:47 UTC, snajima requested changes
great second PR! let's create test cases for the Magazine/new WeeklyDebrief model and address some of the mentioned issues to get this merged!

2023-03-14 18:47 UTC, snajima commented on package.json
> +    "typescript": "^4.0.5",
why are we downgrading? document a reason in your pr description or revert this change

2023-03-14 18:47 UTC, snajima commented on package.json
> +    "eslint-plugin-import": "^2.27.5",
what's all the eslint stuff for? also needs docoumenting

2023-03-15 17:13 UTC, SashaLoayza requested changes
I agree with Shungo that we shouldn't downgrade the typescript version. If adding the line to ignore import/named error in .eslintrc works, we should do that.

2023-03-15 23:45 UTC, katesliang commented
prod

2023-03-20 19:00 UTC, snajima approved these changes
good job isaac 🎉 !! super proud

2023-03-20 19:14 UTC, SashaLoayza approved these changes

2023-03-20 19:15 UTC, merged